module.exports = {
     BLOCKER: 'blocker',
     ERROR: 'error',
     MANDATORY: 'mandatory',

     HEATING: 'Heating',
     COOLING: 'Cooling',

     stateArray: [
        '',
        'AL',
        'AK',
        'AZ',
        'AR',
        'CA',
        'CO',
        'CT',
        'DE',
        'DC',
        'FL',
        'GA',
        'HI',
        'ID',
        'IL',
        'IN',
        'IA',
        'KS',
        'KY',
        'LA',
        'ME',
        'MD',
        'MA',
        'MI',
        'MN',
        'MS',
        'MO',
        'MT',
        'NE',
        'NV',
        'NH',
        'NJ',
        'NM',
        'NY',
        'NC',
        'ND',
        'OH',
        'OK',
        'OR',
        'PA',
        'RI',
        'SC',
        'SD',
        'TN',
        'TX',
        'UT',
        'VT',
        'VA',
        'WA',
        'WV',
        'WI',
        'WY'
    ],

   buildingShapes: [
       'rectangular',
       'town_house'
   ],

     assessmentTypes: [
        'initial',
        'final',
        'qa',
        'alternative',
        'test',
        'corrected',
        'mentor',
        'preconstruction',
        // Note that the 'void' option is omitted by default when rendering assessment type input because it
        // is only available to administrators using the "batch update" feature
        'void',
    ],

     orientationArray: [
        'north',
        'north_east',
        'east',
        'south_east',
        'south',
        'south_west',
        'west',
        'north_west'
    ],

     townHouseWallOrientations: [
         'back_front',
        'back_right_front',
        'back_front_left'
     ],

     zoneWallSides: [
         'back',
         'front',
         'left',
         'right'
     ],

     tiltArray: [
        'flat',
        'low_slope',
        'medium_slope',
        'steep_slope',
    ],
     roofAssemblyCode: [
        'rfwf00co',
        'rfwf00rc',
        'rfwf11co',
        'rfwf13co',
        'rfwf15co',
        'rfwf19co',
        'rfwf21co',
        'rfwf27co',
        'rfwf30co',
        'rfrb00co',
        'rfps00co',
        'rfps11co',
        'rfps13co',
        'rfps15co',
        'rfps19co',
        'rfps21co',
        'rfwf00wo',
        'rfwf00lc',
        'rfwf11wo',
        'rfwf13wo',
        'rfwf15wo',
        'rfwf19wo',
        'rfwf21wo',
        'rfwf27wo',
        'rfwf30wo',
        'rfrb00wo',
        'rfps00wo',
        'rfps11wo',
        'rfps13wo',
        'rfps15wo',
        'rfps19wo',
        'rfps21wo',
        'rfps00rc',
        'rfps11rc',
        'rfps13rc',
        'rfps15rc',
        'rfps19rc',
        'rfps21rc',
        'rfrb00rc',
        'rfwf00tg',
        'rfwf11rc',
        'rfwf13rc',
        'rfwf15rc',
        'rfwf19rc',
        'rfwf21rc',
        'rfwf27rc',
        'rfwf30rc',
        'rfps00lc',
        'rfps11lc',
        'rfps13lc',
        'rfps15lc',
        'rfps19lc',
        'rfps21lc',
        'rfwf11lc',
        'rfwf13lc',
        'rfwf15lc',
        'rfwf19lc',
        'rfwf21lc',
        'rfwf27lc',
        'rfwf30lc',
        'rfps00tg',
        'rfps11tg',
        'rfps13tg',
        'rfps15tg',
        'rfps19tg',
        'rfps21tg',
        'rfwf11tg',
        'rfwf13tg',
        'rfwf15tg',
        'rfwf19tg',
        'rfwf21tg',
        'rfwf27tg',
        'rfwf30tg',
        'rfrb00lc',
        'rfrb00tg',
        'rfwf03co',
        'rfwf03wo',
        'rfwf03rc',
        'rfwf03lc',
        'rfwf03tg',
        'rfwf07co',
        'rfwf07wo',
        'rfwf07rc',
        'rfwf07lc',
        'rfwf07tg',
        'rfwf25co',
        'rfwf25wo',
        'rfwf25rc',
        'rfwf25lc',
        'rfwf25tg',
        'rfps03co',
        'rfps03wo',
        'rfps03rc',
        'rfps03lc',
        'rfps03tg',
        'rfps07co',
        'rfps07wo',
        'rfps07rc',
        'rfps07lc',
        'rfps07tg'
    ],
     roofColor: [
        'white',
        'light',
        'medium',
        'medium_dark',
        'dark',
        'cool_color'
    ],
     roofType: [
        'vented_attic',
        'cath_ceiling'
    ],
     ceilingAssemblyCode: [
        'ecwf00',
        'ecwf03',
        'ecwf06',
        'ecwf09',
        'ecwf11',
        'ecwf13',
        'ecwf15',
        'ecwf19',
        'ecwf21',
        'ecwf25',
        'ecwf30',
        'ecwf35',
        'ecwf38',
        'ecwf44',
        'ecwf49',
        'ecwf55',
        'ecwf60'
    ],

     kneeWallAssemblyCodes: [
        'kwwf00',
        'kwwf03',
        'kwwf07',
        'kwwf11',
        'kwwf13',
        'kwwf15',
        'kwwf19',
        'kwwf21',
    ],

     foundationType: [
        'uncond_basement',
        'cond_basement',
        'vented_crawl',
        'unvented_crawl',
        'slab_on_grade'
    ],

     foundationInsulationLevels: [
         0, // Any foundation types
         5, // Only Slab on grade foundation type
        11, // Any foundation types besides Slab on grade
        19  // Any foundation types besides Slab on grade
     ],

     floorAssemblyCode: [
        'efwf00ca',
        'efwf03ca',
        'efwf07ca',
        'efwf11ca',
        'efwf13ca',
        'efwf15ca',
        'efwf19ca',
        'efwf21ca',
        'efwf25ca',
        'efwf30ca',
        'efwf35ca',
        'efwf38ca'
    ],

     windowAndSkylightCode: [
        'scna',
        'scnw',
        'stna',
        'dcaa',
        'dtaa',
        'thmabw',
        'stnw',
        'dcaw',
        'dtaw',
        'dpeaw',
        'dpeaaw',
        'dseaw',
        'dseaaw',
        'dseaa',
        'dcab',
        'dtab',
        'dpeaab',
        'dseab'
    ],

     wallAssemblyCode: [
        'ewwf00wo',
        'ewwf00st',
        'ewwf00vi',
        'ewwf03wo',
        'ewwf07wo',
        'ewwf11wo',
        'ewwf13wo',
        'ewwf15wo',
        'ewwf19wo',
        'ewwf21wo',
        'ewps00wo',
        'ewps03wo',
        'ewps07wo',
        'ewps11wo',
        'ewps13wo',
        'ewps15wo',
        'ewps19wo',
        'ewps21wo',
        'ewov19wo',
        'ewov21wo',
        'ewov27wo',
        'ewov33wo',
        'ewov38wo',
        'ewov19st',
        'ewov21st',
        'ewov27st',
        'ewov33st',
        'ewov38st',
        'ewcb00st',
        'ewcb03st',
        'ewcb06st',
        'ewsb00st',
        'ewps00st',
        'ewps03st',
        'ewps07st',
        'ewps11st',
        'ewps13st',
        'ewps15st',
        'ewps19st',
        'ewps21st',
        'ewwf00al',
        'ewwf03st',
        'ewwf07st',
        'ewwf11st',
        'ewwf13st',
        'ewwf15st',
        'ewwf19st',
        'ewwf21st',
        'ewwf00br',
        'ewwf03vi',
        'ewwf07vi',
        'ewwf11vi',
        'ewwf13vi',
        'ewwf15vi',
        'ewwf19vi',
        'ewwf21vi',
        'ewwf03al',
        'ewwf07al',
        'ewwf11al',
        'ewwf13al',
        'ewwf15al',
        'ewwf19al',
        'ewwf21al',
        'ewwf03br',
        'ewwf07br',
        'ewwf11br',
        'ewwf13br',
        'ewwf15br',
        'ewwf19br',
        'ewwf21br',
        'ewps00vi',
        'ewps03vi',
        'ewps07vi',
        'ewps11vi',
        'ewps13vi',
        'ewps15vi',
        'ewps19vi',
        'ewps21vi',
        'ewov19vi',
        'ewov21vi',
        'ewov27vi',
        'ewov33vi',
        'ewov38vi',
        'ewps00al',
        'ewps03al',
        'ewps07al',
        'ewps11al',
        'ewps13al',
        'ewps15al',
        'ewps19al',
        'ewps21al',
        'ewov19al',
        'ewov21al',
        'ewov27al',
        'ewov33al',
        'ewov38al',
        'ewps00br',
        'ewps03br',
        'ewps07br',
        'ewps11br',
        'ewps13br',
        'ewps15br',
        'ewps19br',
        'ewps21br',
        'ewov19br',
        'ewov21br',
        'ewov27br',
        'ewov33br',
        'ewov38br',
        'ewbr00nn',
        'ewbr05nn',
        'ewbr10nn',
        'ewcb00nn',
        'ewcb03nn',
        'ewcb06nn',
        'ewcb00br',
        'ewcb03br',
        'ewcb06br',
        'ewov25wo',
        'ewov35wo',
        'ewov25st',
        'ewov35st',
        'ewov25vi',
        'ewov35vi',
        'ewov25al',
        'ewov35al',
        'ewov25br',
        'ewov35br'
    ],

     heatingTypeOptions: [
        'none',
        'central_furnace',
        'wall_furnace',
        'boiler',
        'heat_pump',
        'baseboard',
        'gchp',
        'mini_split',
        'wood_stove',
    ],

     ductlessHeatingTypes: [
        'central_furnace',
        'gchp',
        'heat_pump',
        'split_dx'
     ],

     heatingFuelOptions: [
        'natural_gas',
        'lpg',
        'fuel_oil',
        'electric',
        'cord_wood',
        'pellet_wood'
    ],

     furnaceAndBoiler: [
        'central_furnace',
        'wall_furnace',
        'boiler'
    ],

     heatingFuelToType: {
        'natural_gas': [
            'central_furnace',
            'wall_furnace',
            'boiler'
        ],
        'lpg': [
            'central_furnace',
            'wall_furnace',
            'boiler'
        ],
        'fuel_oil': [
            'central_furnace',
            'wall_furnace',
            'boiler'
        ],
        'electric': [
            'central_furnace',
            'heat_pump',
            'mini_split',
            'gchp',
            'baseboard',
            'boiler'
        ],
        'cord_wood': ['wood_stove'],
        'pellet_wood': ['wood_stove'],
    },

     coolingTypeOptions: [
        'none',
        'packaged_dx',
        'split_dx',
        'heat_pump',
        'gchp',
        'dec',
        'mini_split'
    ],

     hvacEfficiencyOptions: [
        'shipment_weighted',
        'user'
     ],

     ductType: [
        'cond_space',
        'uncond_attic',
        'uncond_basement',
        'vented_crawl',
        'unvented_crawl',
        'under_slab',
        'exterior_wall',
        'outside'
    ],

     ductType_alwaysValid: [
        'cond_space',
        'under_slab',
        'exterior_wall',
        'outside'
    ],

     hotWaterCategories: [
         'unit',
        'combined'
     ],

     hotWaterFuel: [
        'natural_gas',
        'lpg',
        'fuel_oil',
        'electric',
    ],

     hotWaterType: [
        'storage',
        'heat_pump',
        'indirect',
        'tankless_coil',
        'tankless'
    ],
}