// DO NOT EDIT THIS FILE.  This file was auto-generated using a script.
// If you need to edit this code, please instead refer to the scripts in types/hes-json/*
// in the hes-rest project
import { HvacPerformance } from '../Enumerations/Enumerations';
import { UpgradeBase } from '../Models/UpgradeBase';
import { UpgradeRep } from './UpgradeRep.type';

export interface ApplicableUpgrade {
    upgrade_rep: UpgradeRep;
    upgrade_info: {
        max_simple_payback: number;
        upgrade_performance?: HvacPerformance;
        class?: UpgradeBase;
        [x: string]: any;
    };
}
