// DO NOT EDIT THIS FILE.  This file was auto-generated using a script.
// If you need to edit this code, please instead refer to the scripts in types/hes-json/*
// in the hes-rest project
import { Building } from './Building.type'

export type WallAssemblyCode = Building['zone']['zone_wall'][number]['wall_assembly_code']

export type WallConstructionType = 'wf' | 'ps' | 'ov' | 'cb' | 'br' | 'sb'

export type WallExteriorFinish = 'wo' | 'st' | 'vi' | 'al' | 'br' | 'nn'

export type FloorAssemblyCode = Building['zone']['zone_floor'][number]['floor_assembly_code']

export type FloorConstructionType = 'wf'

export type FloorExteriorFinish = 'ca'

//two step is needed here.
type Window = Exclude<Building['zone']['zone_wall'][number]['zone_window'], undefined>
export type WindowAndSkylightCode = Window['window_code']

export type RoofAssemblyCode = Building['zone']['zone_roof'][number]['roof_assembly_code']

export type RoofConstructionType = 'wf' | 'rb' | 'ps'

export type RoofExteriorFinish = 'co' | 'wo' | 'rc' | 'lc' | 'tg'

export type CeilingAssemblyCode = Building['zone']['zone_roof'][number]['ceiling_assembly_code']

export type CeilingConstructionType = 'wf'

export type CeilingExteriorFinish = ''

type KneeWall = Exclude<Building['zone']['zone_roof'][number]['knee_wall'], undefined>
export type KneeWallAssemblyCode = KneeWall['assembly_code']

export type KneeWallConstructionType = 'wf'

export type KneeWallExteriorFinish = ''
