// DO NOT EDIT THIS FILE.  This file was auto-generated using a script.
// If you need to edit this code, please instead refer to the scripts in types/hes-json/*
// in the hes-rest project
import { HomeEnergyScore } from './HomeEnergyScore.type'
export type Building = HomeEnergyScore['building_unit']
