// DO NOT EDIT THIS FILE.  This file was auto-generated using a script.
// If you need to edit this code, please instead refer to the scripts in types/hes-json/*
// in the hes-rest project
export enum PeriodType {
    hour = 'hour',
    day = 'day',
    week = 'week',
    month = 'month',
    year = 'year',
}

export enum ResourceType {
    electric = 'electric',
    demand = 'demand',
    natural_gas = 'natural_gas',
    lpg = 'lpg',
    fuel_oil = 'fuel_oil',
    cold_water = 'cold_water',
    hot_water = 'hot_water',
    carbon = 'carbon_emissions',
    currency = 'currency',
    heat_flow = 'heat_flow',
    source = 'source',
    site_gen_electric = 'site_gen_electric',
    cord_wood = 'cord_wood',
    pellet_wood = 'pellet_wood',
    score = 'score',
    all = 'all',
}

export enum EndUse {
    building_equipment = 'building_equipment',
    circulation = 'circulation',
    cooling = 'cooling',
    generation = 'generation',
    heating = 'heating',
    hot_water = 'hot_water',
    large_appliance = 'large_appliance',
    lighting = 'lighting',
    small_appliance = 'small_appliance',
}

export interface SimulationResult {
    quantity: number
    resource_type: ResourceType
    period_type?: PeriodType
    period_number?: number
    end_use?: EndUse
    units?: number
}

export interface OsWorkflowResult {
    end_use: SimulationResult[]
}
