// DO NOT EDIT THIS FILE.  This file was auto-generated using a script.
// If you need to edit this code, please instead refer to the scripts in types/hes-json/*
// in the hes-rest project
import { Building } from './Building.type';

export type RoofContextType = Exclude<Building['zone']['zone_roof'][number], undefined>;

export type HvacContextType = Exclude<Building['systems']['hvac'][number], undefined>;

export type FloorContextType = Exclude<Building['zone']['zone_floor'][number], undefined>;

export type HotWaterType = Exclude<Building['systems']['domestic_hot_water'], undefined>;

export type WallContextType = Exclude<Building['zone']['zone_wall'][number], undefined>;
