// DO NOT EDIT THIS FILE.  This file was auto-generated using a script.
// If you need to edit this code, please instead refer to the scripts in types/hes-json/*
import { HomeEnergyScore } from './HomeEnergyScore.type'
export const UPGRADES_SCHEMA_VERSION = '1.0'
export type UpgradeRep = Exclude<HomeEnergyScore['building_upgrades'], undefined | 'version'>['upgrades'][number]
